version: "2"

services:
  esdata:
    image: busybox
    container_name: esdata
    volumes:
      - /opt/elasticsearch/data
    command:
      /bin/true
      
  elasticsearch:
    image: elasticsearch
    container_name: elasticsearch
    volumes_from:
      - esdata
    environment:
      CURATOR_ARGS: delete indices --older-than 30 --time-unit days --timestring '%Y.%m.%d'
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

  logstash:
    image: logstash
    container_name: logstash
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    command: |
      -e '
      input {
        tcp {
          port => 3030
          type => meta
          add_field => { "protocol" => "tcp" }
          codec => json
        }
        udp {
          port => 3030
          type => meta
          add_field => { "protocol" => "udp" }
          codec => json
        }
      }
      output {
        elasticsearch {
          hosts => ["elasticsearch:9200"]
        }
        tcp {
          codec => json_lines
          host => "logs"
          port => 3000
          mode => "client"
        }
      }'
    ports:
      - "3030:3030/udp"
      - "3030:3030"

  kibana:
    image: kibana
    container_name: kibana
    ports:
      - "80:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      KIBANA_USER: admin
      KIBANA_PASS: secret
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

  logsdata:
    image: busybox
    container_name: logsdata
    volumes:
      - /data
    command:
      /bin/true

  logs:
    build: logstash-notifier
    container_name: logs
    volumes_from:
      - logsdata
    env_file:
      - ./config.env
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    ports:
      - "8080:8080"

